export const actiontypes={
  SET_PRODUCTS:"SET_PRODUCTS",
  SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS:"REMOVE_SELECTED_PRODUCTS",
  ADD_CART:"ADD_CART",
  DELETE_CART:"DELETE_CART",
};